# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb3d1e2a578f25e3e5f986c319534555525b453f7818cf2fa88e3cc1ace727c8f4b19fa375ce5c28a0871f207779dbc910cfe6a31759e2fd01dfef031108856

test:
  secret_key_base: 425526491055f21978ed8d6ae6340442cb6deb021b514909c36e988608d049337e65c1d88aa33ab4dd8006d52f44322a98cb84a25c945bbcfd92929612d64bd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
